### ISSUE TITLE
BUG: saving a value not in autocomplete source isn't saved to database

### ISSUE THREAD

**Issue by christopherdarling** [tractorcow/silverstripe-autocomplete#10]
If I select an existing value from the autocomplete dropdown the value is saved to the database fine, but if I type in a custom value (or just type out a value that already exists in the dropdown instead of selecting it) the value isn't saved.

**Comment by christopherdarling** [comment]
My apologies, we were tracking master for our composer requirement which is now for 3.2. Closing this ticket

**Comment by christopherdarling** [comment]
I've just run into this problem again on a 3.1 site, looking at the composer.json file master or tag 3.3.0 is 3.1 compatible so reopening this ticket

**Comment by tractorcow** [comment]
Fixed with #15 and new tag 3.3.1 is available
