### ISSUE TITLE
On focus selection

### ISSUE THREAD

**Issue by giovdk21** [tractorcow/silverstripe-autocomplete#12]
Hello,
I'm not sure if it is me using it in the wrong way or if this could be improved, but `$('.field.autocomplete input.text')` it is not returning/selecting anything.

I changed it to be:

```javascript
		$('form').on('focus', 'input.autocomplete.text', function(e) {

		var input = $(e.target);
```

does it make sense or do you think it is now too generic?

The class of my autocomplete field is just `class="autocomplete text"` and there is no parent element having the field class.

Thanks.

**Comment by tractorcow** [comment]
Hm, that's odd. I'd have to check it out and test it.

Do you want to submit a pull request to fix this?

**Comment by giovdk21** [comment]
Hello,
at the moment I'm not using this add-on anymore but the change was just the one I mentioned on my first message.

It could very well be something related to the specific site I was working on as it is an old one and maybe the form is generated in a slightly different way and the field list was also using a CompositeField to group a couple of fields.

Thanks.

**Comment by jonom** [comment]
Not sure if this is the same issue or not but currently if you load a form and this field is already focused, typing in the field doesn't initiate the auto-complete behaviour. You need to blur the field and re-focus it, then change the text in the field (e.g. by deleting a letter and re-typing it) to trigger the search.
