### ISSUE TITLE
Error with SS 3.2.0 beta 2

### ISSUE THREAD

**Issue by aledbrown** [tractorcow/silverstripe-autocomplete#13]
Just a head's up that the silverstripe-autocomplete module doesn't quite work with SS 3.2.0 b2. I get the following PHP Error Log:

PHP Catchable fatal error:  Argument 1 passed to AutoCompleteField::Suggest() must be an instance of HTTPRequest, instance of SS_HTTPRequest given, called in /framework/control/RequestHandler.php on line 288 and defined in /silverstripe-autocomplete/code/AutoCompleteField.php on line 231

Stranger still when looking at line 231 the Suggest function appears to be passing a HTTPRequest anyway.

I just wanted to test a large Silverstripe site with the new 3.2 beta incase there were any issues and this is the first one I came to so I thought I'd report it. Still getting to grips with the many changes. Looks like a big release.

**Comment by tractorcow** [comment]
Fixed and added tag for 3.2.1
