### ISSUE TITLE
Browser crashes

### ISSUE THREAD

**Issue by Firesphere** [tractorcow/silverstripe-autocomplete#25]
The moment I want to start a search, the browser crashes. Even a bare Chromium just stalls and sits there doing nothing.

**Comment by tractorcow** [comment]
Oh no!

Does it crash all browsers or just chrome?

**Comment by Firesphere** [comment]
Chromium, Firefox dev edition, Safari.

It's kinda weird, because I had a has_one selection dropdown, which loads the entire dataset (a few thousands of records), which didn't totally crash the browser. It seems the ajax call does something funny?

**Comment by Firesphere** [comment]
Addition:
It works, until I try to select the autocomplete-field. Then all hell breaks loose.

**Comment by tractorcow** [comment]
Yikes, that sounds like a serious problem... I have no idea what's causing it. :D

**Comment by Firesphere** [comment]
It's the jquery-UI method that's terrible. Using another autocompleter works perfectly fine. I guess jquery UI is crap

**Comment by cwchong** [comment]
looking at the source (I haven't tried tbh), it seems you are using a db query each time characters are typed, and returning these partial matches to jquery (i.e. passing a string url source), is that correct?

Wouldn't it be more efficient to just return the full dataset as array to jquery at once, and leave the filtering to jquery, hence running only a single db query?

**Comment by tractorcow** [comment]
> Wouldn't it be more efficient to just return the full dataset as array to jquery at once, and leave the filtering to jquery, hence running only a single db query?

Except some sites have 10s of thousands of records... if you don't want autocomplete, you should just be using ListBox which does a full pre-load of all records for autocomplete.
