### ISSUE TITLE
Can't clear selection

### ISSUE THREAD

**Issue by jonom** [tractorcow/silverstripe-autocomplete#26]
By default, it doesn't seem possible to clear the selected record, i.e. set it to ID=0. If you delete the text in the field and hit Save, the value reappears on select.

To make this behaviour possible you can do `$field->setRequireSelection(false)` but that leads to an error upon save if you type text in the field but don't choose a record. _(ERROR [User Warning]: DataObject::get_by_id passed a non-numeric ID)_

**Comment by tractorcow** [comment]
> To make this behaviour possible you can do $field->setRequireSelection(false) but that leads to an error upon save if you type text in the field but don't choose a record. (ERROR [User Warning]: DataObject::get_by_id passed a non-numeric ID)

What is posted back to the server in this case?

    public function Value() should shortcut to return '' if it's dataValue() is empty.
    
   Want to test / PR?

**Comment by jonom** [comment]
Yeah there's a few other things I want to test and fix up too, will try to get to them soon and submit some patches
