### ISSUE TITLE
BUG: Multi-word search terms

### ISSUE THREAD

**Issue by jonom** [tractorcow/silverstripe-autocomplete#27]
In a multi-word search term only the final word is used in a search, due to this loop within a loop, which keeps overwriting the previous filters: https://github.com/tractorcow/silverstripe-autocomplete/blob/master/code/AutoCompleteField.php#L495

Due to the limitation documented here: https://github.com/silverstripe/silverstripe-framework/issues/1378 I'm not sure the intended effect can be accomplished with a single filter expression.

Additionally if the intended behaviour worked, typing more than one word would have the effect of increasing the number of matches instead of narrowing them down, which is counter-productive.

I have a few different ideas for fixing this:

#### 1. The easy 'literal' way

Since this is billed as an 'auto complete' field rather than a search field it may be a better default behaviour to match on the full literal string rather than splitting up the string and treating each word as a key word. It's very easy to patch in the behaviour and works well for what I was trying to use this field for. Potential limitation is that if you've set the field to search across multiple fields, you can't enter a keyword that will match on one field and then a separate keyword that will match on another field, so you can only effectively search one field at a time. That could be made clear with some descriptive text on the field though e.g. _"Type a Member name OR Company name"_

#### 2. The complex 'fuzzy' way

* Split up search term as keywords as per original intention, but also include the complete search term in the array, so a literal match is possible
* Make a separate results list for each field being searched, assigning a score to each record according to how many keyword matches were made. Sort based on Score DESC so more keyword matches = higher in the list.
* Merge the lists and where a record is in more than one list, combine the scores. Return only the highest-scoring records

#### 3.  ⚡💥 🔥  The ultimate has one picker field 🔥 💥⚡ 

This isn't really a fix for this bug but a grand vision for the future.

1. Choose either of the previous methods for improving the auto-complete search algorithm
2. Add pagination or a 'Load more' button to the results list
3. Distinguish a search term from the stored value by using placeholder text to indicate the stored value
4. When blurring the text field, clear the search term if a record wasn't selected so the stored record can be seen again
5. Add a 'x' clear selection button for clearing the has_one relation
6. Add an 'Advanced search' link which loads a detailed search form akin to [GridFieldAddExistingSearchButton](GridFieldAddExistingSearchButton) for when you can't find what you want with auto-complete.

Can you guess which solution I like best? This would be an asset for the project I think, but given how critical this bug is I think it would be best to start with the first solution, then maybe implement the second as time permits, then make a frankenstein ultimate has_one field once those pieces are in place (if they ever are).

Thoughts?

**Comment by jonom** [comment]
Note: gridfield 'add existing' auto-complete [seems to function](http://api.silverstripe.org/3.3/source-class-GridFieldAddExistingAutocompleter.html#187-225) like solution (1) outlined above

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-autocomplete/pull/28
