### ISSUE TITLE
Holder: SS4 compatibility

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow/silverstripe-autocomplete#31]
Hey @tractorcow - just logging this is as a placeholder for SilverStripe 4 compatibility.

## Pre-requisites

- [ ] Branch current master off to `3` and/or `3.4`
- [ ] Update composer alias on master to `4.0.x-dev`

## Requirements

- [ ] Add namespacing including [upgrader](https://github.com/silverstripe/silverstripe-upgrader)
- [ ] Implement core namespacing throughout (`upgrade`)
- [ ] Tweak framework changes and/or CSS/Javascript selectors
- [ ] Update template locations, tests, CI configuration, composer configuration
- [ ] Update documentation/readme

**Comment by wilr** [comment]
@robbieaverill You happen to be taking on this? Need the module in the next couple weeks so happy to upgrade it as long as no one else has started it

**Comment by robbieaverill** [comment]
Hey @wilr - I was going to but got dragged off. I didn't start it. Go for it!

**Comment by wilr** [comment]
👍
