### ISSUE TITLE
Search across multiple fields not returning appropriate results

### ISSUE THREAD

**Issue by jcop007** [tractorcow/silverstripe-autocomplete#36]
This issue was introduced after the fix for #32 was released.
We've got an autocomplete field which allows the user to search either firstname or surname in the autocomple field in order to find a member record.  Since the query has been changed from filterAny to filter it will now only return a result if the keyword is in both the firstname and surname.  e.g if you type "Jam" it will find Jamie Jamieson by not James Blunt.  

AutoCompleteField::create('MemberID','Member','',null,null,'Member',array('FirstName', 'Surname')

**Comment by tractorcow** [comment]
Right, so the fix would be a partial revert and re-implementation of #33 so that it used filterAny(), but used the updated two-level loop that included all field / keyword combination?

**Comment by patricknelson** [comment]
The [potentially bad] way I typically solve problems like these in my own code is to use `CONCAT(field1, field2, ...)` and then do a `LIKE` search on that. This results in a much simpler `WHERE` clause. Is that feasible here at the framework level or is that too dependent upon the underlying database (even though the only officially supported DBMS is MySQL)?

**Comment by tractorcow** [comment]
Better to use filterAny() instead, otherwise it'll be order dependent.

**Comment by patricknelson** [comment]
Doesn’t matter to me as long as the fix here doesn’t break the issue raised in #32.

**Comment by tractorcow** [comment]
Fixed with #32

**Comment by patricknelson** [comment]
> Fixed with #32

For the record, fixed with  #37, this bug was **caused** by my PR #33 (issue #32) 😄
