### ISSUE TITLE
Jquery is missing - SS4 release 

### ISSUE THREAD

**Issue by josephlewisnz** [tractorcow/silverstripe-autocomplete#52]
Jquery is missing and has been remove from SS4.x

I've seen this issue around
https://github.com/silverstripe/silverstripe-cms/issues/2853
https://github.com/symbiote/silverstripe-memberprofiles/issues/184

Looks like you have a fix on ss5 release. 

I'll create a pull request with a fix or partial for the 4 branch

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-autocomplete/pull/53 thanks @josephlewisnz
